Dmitrii_Matvienko Tasks 1-10
MatvienkoDO/ui-internship-lwo2 pull request #1
Opened 2019-09-09 18:54 UTC by MatvienkoDO

2019-09-10 14:19 UTC, vovcyan requested changes

2019-09-10 14:19 UTC, vovcyan commented on tasks/5_profile-lookup/profile-lookup.js
> +  if (prop in contact === false) {
It is not a good way to use === false or === true in conditions
For example you can replace it by:
if ( !(prop in contact)) or by something else

2019-09-10 14:19 UTC, vovcyan commented on tasks/7_random-fraction/random-fraction.js
> +  return Math.random();
Function must return decimal value
For example: 0.1, 0.2, ... , 0.9

2019-09-10 14:19 UTC, vovcyan commented on tasks/9_find-numbers/find-numbers.js
> +      .filter((n) => !isNaN(n));
I think it's unnecessary way

2019-09-10 15:13 UTC, MatvienkoDO commented on tasks/5_profile-lookup/profile-lookup.js
> +  if (prop in contact === false) {
done

2019-09-10 15:13 UTC, MatvienkoDO commented on tasks/7_random-fraction/random-fraction.js
> +  return Math.random();
done

2019-09-10 15:13 UTC, MatvienkoDO commented on tasks/9_find-numbers/find-numbers.js
> +      .filter((n) => !isNaN(n));
done

2019-09-10 17:10 UTC, alexkond commented on tasks/8_factorize-number/factorize-number.js
> +/* solution through tail-recursion
Tail optimization is neat. I like it!

2019-09-10 17:12 UTC, alexkond approved these changes

2019-09-10 18:14 UTC, vadeneev commented on tasks/10_remove-whitespaces/remove-whitespaces.js
> +      .split(' ')
Have you tried to measure what could be faster - split join or regexp ?

2019-09-10 18:17 UTC, vadeneev commented on tasks/1_golf-score/golf-score.js
> +  if (strokes === 1) {
It works! However, how do you feel about switch case in that particular case ? It looks like you did it, mean switch without switch

2019-09-10 18:48 UTC, vadeneev approved these changes

2019-09-10 18:48 UTC, vadeneev commented on tasks/2_convert-to-f/convert-to-f.js
> +  return temperature * 1.8 + 32;
For example temperature = 26 results with 78.80000000000001 - how do you like it ? How about rounding values ?

2019-09-10 18:48 UTC, vadeneev commented on tasks/4_stand-in-line/stand-in-line.js
> +  array.push(element);
What i don't like in this function - is that we are mutating array we passing to it. It is better to use pure functions https://hackernoon.com/javascript-and-functional-programming-pt-3-pure-functions-d572bb52e21c

second thing  - I bet, that .slice(1) would be significantly faster

2019-09-10 18:48 UTC, vadeneev commented on tasks/6_reverse-string/reverse-string.js
> +      .join('');
Tests passed.
But, how about `foo 𝌆 bar mañana mañana` ? try it ;)

2019-09-10 18:48 UTC, vadeneev commented on tasks/6_reverse-string/reverse-string.js
> +      .join('');
it is not change request as far as tests passed

2019-09-10 18:48 UTC, vadeneev commented on tasks/5_profile-lookup/profile-lookup.js
> +      .find((contact) => contact && contact.firstName === firstName);
Oh, right, undefined

2019-09-11 05:34 UTC, vadeneev commented on tasks/4_stand-in-line/stand-in-line.js
> +  array.push(element);
meh, it should mutate

2019-09-11 05:35 UTC, vadeneev approved these changes

2019-09-11 05:50 UTC, vovcyan approved these changes

2019-09-11 05:51 UTC, merged

2019-09-11 05:53 UTC, vadeneev commented on tasks/9_find-numbers/find-numbers.js
> +  const regexResult = str.match(/\d/g);
Should we treat s123d as a string with one number ?

2019-09-11 07:12 UTC, MatvienkoDO commented on tasks/10_remove-whitespaces/remove-whitespaces.js
> +      .split(' ')
I have measured both options. Measurement was showing that split-join is faster. 69 against 107. It means that in average replace(/\s/g, '') takes 1.55 times more time.

2019-09-11 07:17 UTC, MatvienkoDO commented on tasks/10_remove-whitespaces/remove-whitespaces.js
> +      .split(' ')
https://drive.google.com/file/d/10queSKlPAlLVFUmNRIkibEzHB8INK6kQ/view?usp=sharing

2019-09-11 08:49 UTC, MatvienkoDO commented on tasks/9_find-numbers/find-numbers.js
> +  const regexResult = str.match(/\d/g);
The task is named 'find numbers'. So, i think that your correction is right