Dmitrii_Matvienko Tasks 91-100
MatvienkoDO/ui-internship-lwo2 pull request #10
Opened 2019-09-23 18:29 UTC by MatvienkoDO

2019-09-24 07:44 UTC, vovcyan requested changes

2019-09-24 07:44 UTC, vovcyan commented on tasks/91_make-a-person/make-a-person.js
> +  return this._firstname;
You're using fields with underscore to make it private. But it's fake private.
Please refactor it and use all power of pattern "module" ;)

2019-09-24 13:48 UTC, MatvienkoDO commented on tasks/91_make-a-person/make-a-person.js
> +  return this._firstname;
I can't use variables from closure instead of function context, because I have only one instance of getFirstName, getLastName, etc in the prototype of Person.
Sure, i can create functions in constructor and assign it to props of this and use actually private variables from closure, but it is bad practice, because it produces a lot of same functions (only with different references to variables from closure) and breaks inheritance in case of call constructor of base class

2019-09-25 12:56 UTC, vovcyan requested changes

2019-09-25 12:56 UTC, vovcyan commented on tasks/98_linked-list/linked-list.js
> +  if (this._size === 0) {
!this._size

2019-09-25 12:56 UTC, vovcyan commented on tasks/99_stack/stack.js
> +    if (this._size === 0) {
The same

2019-09-26 05:57 UTC, savchukm commented on tasks/98_linked-list/linked-list.js
> +  const oldLast = this._lastNode;
You are using const and ES5 class syntax mixed, but there are no "only es5" in task description. By default ES6 is preferred

2019-09-26 08:33 UTC, vovcyan approved these changes

2019-09-26 08:37 UTC, savchukm approved these changes

2019-09-26 08:45 UTC, merged