Dmitrii_Matvienko Tasks 11-20
MatvienkoDO/ui-internship-lwo2 pull request #2
Opened 2019-09-10 14:32 UTC by MatvienkoDO

2019-09-10 17:25 UTC, alexkond requested changes

2019-09-10 17:25 UTC, alexkond commented on tasks/16_repeat-string/repeat-string.js
> +  let result = '';
Look closely to `String` prototype. There's a method designed for this case.

2019-09-10 17:25 UTC, alexkond commented on tasks/17_truncate-string/truncate-string.js
> +  if (str.length <= maxLength) {
I think for this case you also could find useful method on `String` prototype.

2019-09-10 17:25 UTC, alexkond commented on tasks/18_humanize-format/humanize-format.js
> +    // right number, continiue work
You could revert this logic to make it
``` javascript
if (//check for invalid num) {
  return '';
}
```

2019-09-11 09:12 UTC, MatvienkoDO commented on tasks/12_title-case/title-case.js
> +        const firstSymbol = word.substr(0, 1).toUpperCase();
I think 'charAt' is better for this task. (Instead of substr)

2019-09-11 09:13 UTC, MatvienkoDO commented on tasks/12_title-case/title-case.js
> +        const rest = word.substr(1).toLowerCase();
substr is legacy. It is better to use substring

2019-09-11 09:35 UTC, MatvienkoDO commented on tasks/20_truncate-array/truncate-array.js
> +  arr.splice(0, n);
It would be better to use slice instead of splice. Function would appear nicer and would not change source arr

2019-09-11 11:33 UTC, vadeneev requested changes

2019-09-11 11:33 UTC, vadeneev commented on tasks/11_find-longest-word/find-longest-word.js
> +/* solution without reduce
This one looks better

2019-09-11 11:33 UTC, vadeneev commented on tasks/12_title-case/title-case.js
> +        const firstSymbol = word.substr(0, 1).toUpperCase();
[0] !?

2019-09-11 11:33 UTC, vadeneev commented on tasks/12_title-case/title-case.js
> +        return `${firstSymbol}${rest}`;
It is not how this stuff is supposed to be used - mean it is a function, which has some stuff under the hood, i suggest to use 'a'+'b' approach

2019-09-12 05:43 UTC, alexkond commented on tasks/12_title-case/title-case.js
> +        return `${firstSymbol}${rest}`;
Yes, Template literals are designed for cases, when you need to create string from strings and variables.

2019-09-12 09:16 UTC, MatvienkoDO commented on tasks/17_truncate-string/truncate-string.js
> +    return str;
there is inconsistency here. In this case function returns incoming string, but in another returns copy

2019-09-12 09:46 UTC, MatvienkoDO commented on tasks/16_repeat-string/repeat-string.js
> +  let result = '';
fixed

2019-09-12 09:48 UTC, MatvienkoDO commented on tasks/17_truncate-string/truncate-string.js
> +  if (str.length <= maxLength) {
I suppose I found it

2019-09-12 09:50 UTC, MatvienkoDO commented on tasks/17_truncate-string/truncate-string.js
> +    return str;
Thanks for attention. Fixed

2019-09-12 09:57 UTC, MatvienkoDO commented on tasks/18_humanize-format/humanize-format.js
> +    // right number, continiue work
Done

2019-09-12 10:03 UTC, MatvienkoDO commented on tasks/12_title-case/title-case.js
> +        const firstSymbol = word.substr(0, 1).toUpperCase();
Indeed 😐

2019-09-12 10:05 UTC, MatvienkoDO commented on tasks/12_title-case/title-case.js
> +        const rest = word.substr(1).toLowerCase();
ok

2019-09-12 10:06 UTC, MatvienkoDO commented on tasks/12_title-case/title-case.js
> +        return `${firstSymbol}${rest}`;
Agree

2019-09-12 10:22 UTC, MatvienkoDO commented on tasks/20_truncate-array/truncate-array.js
> +  arr.splice(0, n);
changed

2019-09-12 11:08 UTC, MatvienkoDO commented on tasks/11_find-longest-word/find-longest-word.js
> +/* solution without reduce
Agree. Used that

2019-09-12 11:12 UTC, vovcyan approved these changes

2019-09-13 05:49 UTC, vadeneev approved these changes

2019-09-13 07:07 UTC, alexkond approved these changes

2019-09-13 07:37 UTC, merged