Dmitrii_Matvienko Tasks 21-30
MatvienkoDO/ui-internship-lwo2 pull request #3
Opened 2019-09-12 11:59 UTC by MatvienkoDO

2019-09-12 12:03 UTC, MatvienkoDO commented on tasks/21_check-letters/check-letters.js
> +export function checkLetters([first, second]) {
Is it enough or I should use Set?

2019-09-13 05:53 UTC, vadeneev commented on tasks/21_check-letters/check-letters.js
> +export function checkLetters([first, second]) {
It is enough, do you thing Set could be used here ? I quite not sure

2019-09-13 05:53 UTC, vadeneev commented on tasks/22_remove-falsy-values/remove-falsy-values.js
> +  return values.filter((value) => value);
You did it before, more elegant way = Boolean

2019-09-13 06:00 UTC, vadeneev submitted a review, later dismissed

2019-09-13 06:00 UTC, vadeneev commented on tasks/24_index-to-insert/index-to-insert.js
> +  arr.push(insertable);
Is it fine for this task to mutate array ?

2019-09-13 06:00 UTC, vadeneev commented on tasks/27_basic-subclasses/basic-subclasses.js
> +const SEX = Object.freeze({
It is fine to have variable declarations on top of file / module / function ( if nothing is not depended on it)

2019-09-13 06:05 UTC, vovcyan submitted a review, later dismissed

2019-09-13 07:10 UTC, alexkond submitted a review, later dismissed

2019-09-13 07:10 UTC, alexkond commented on tasks/28_vowel-count/vowel-count.js
> +// eslint-disable-next-line no-undef
Cheater

2019-09-13 07:10 UTC, alexkond commented on tasks/29_remove-duplicates/remove-duplicates.js
> +  // eslint-disable-next-line no-undef
Cheater

2019-09-13 07:43 UTC, MatvienkoDO commented on tasks/21_check-letters/check-letters.js
> +export function checkLetters([first, second]) {
ok

2019-09-13 08:08 UTC, MatvienkoDO commented on tasks/22_remove-falsy-values/remove-falsy-values.js
> +  return values.filter((value) => value);
fixed

2019-09-13 08:09 UTC, MatvienkoDO commented on tasks/24_index-to-insert/index-to-insert.js
> +  arr.push(insertable);
Made without mutation

2019-09-13 08:10 UTC, MatvienkoDO commented on tasks/27_basic-subclasses/basic-subclasses.js
> +const SEX = Object.freeze({
Moved it

2019-09-13 08:10 UTC, MatvienkoDO commented on tasks/28_vowel-count/vowel-count.js
> +// eslint-disable-next-line no-undef
Fixed problem causing it

2019-09-13 08:13 UTC, MatvienkoDO commented on tasks/28_vowel-count/vowel-count.js
> +// eslint-disable-next-line no-undef
Actually there is no need to use Set here, because it does not guarantee quick search. Made array here as it was

2019-09-13 08:14 UTC, MatvienkoDO commented on tasks/29_remove-duplicates/remove-duplicates.js
> +  // eslint-disable-next-line no-undef
Fixed problem causing it

2019-09-13 13:18 UTC, vadeneev requested changes

2019-09-13 13:18 UTC, vadeneev commented on tasks/27_basic-subclasses/basic-subclasses.js
> +    this.sex = SEX.MALE;
I think, human should have sex, not Man or Woman itself

2019-09-13 16:20 UTC, vadeneev approved these changes

2019-09-16 08:08 UTC, vovcyan approved these changes

2019-09-16 09:23 UTC, merged