Dmitrii_Matvienko Tasks 41-50
MatvienkoDO/ui-internship-lwo2 pull request #5
Opened 2019-09-16 11:05 UTC by MatvienkoDO

2019-09-17 17:22 UTC, MatvienkoDO commented on tasks/44_time-simulation/time-simulation.js
> +export class SimTime {
@alexkond asked us to make it in 'before es6' manner. Without 'class' language construction

2019-09-18 05:47 UTC, vovcyan requested changes

2019-09-18 05:47 UTC, vovcyan commented on tasks/50_camel-case/camel-case.spec.js
> -    test("'hello case'.camelCase() should return 'HelloCase'", () => {
Please revert this change

2019-09-18 05:47 UTC, vovcyan commented on tasks/50_camel-case/README.md
> -Write simple .camelCase method for strings. All words must have their first letter capitalized without spaces.
Revert it

2019-09-18 05:50 UTC, savchukm requested changes

2019-09-18 05:50 UTC, savchukm commented on tasks/44_time-simulation/time-simulation.js
> +SimTime.prototype.get = function() {
`this.get = ...` will be enough

2019-09-18 05:50 UTC, savchukm commented on tasks/50_camel-case/camel-case.spec.js
> +        expect('camel case word'.camelCase()).toBe("camelCaseWord");
It is not allowed to change test suites. 
There are 2 types of camel cases: upper camel case and lower camel case. By the way, It is not a mistake

2019-09-18 05:50 UTC, savchukm commented on tasks/50_camel-case/README.md
> +Write simple .camelCase method for strings. All words except first must have their first letter capitalized without spaces.
Revert these changes

2019-09-18 05:50 UTC, savchukm commented on tasks/50_camel-case/camel-case.js
> +String.prototype.camelCase = function() {
Please make this function working with correct tests

2019-09-18 07:48 UTC, alexkond submitted a review, later dismissed

2019-09-18 17:04 UTC, alexkond approved these changes

2019-09-19 05:08 UTC, savchukm approved these changes

2019-09-19 06:54 UTC, vovcyan approved these changes

2019-09-19 06:54 UTC, merged