Dmitrii_Matvienko Tasks 51-60
MatvienkoDO/ui-internship-lwo2 pull request #6
Opened 2019-09-17 11:11 UTC by MatvienkoDO

2019-09-17 13:08 UTC, MatvienkoDO commented
Add examples (@example)

2019-09-17 17:12 UTC, vovcyan requested changes

2019-09-17 17:12 UTC, vovcyan commented on tasks/51_abbreviated-name/abbreviated-name.js
> + * makes abbreviated form of name
Please add example

2019-09-17 17:14 UTC, MatvienkoDO commented on tasks/51_abbreviated-name/abbreviated-name.js
> + * makes abbreviated form of name
Yes, sure. I wrote for myself comment (https://github.com/MatvienkoDO/ui-internship-lwo2/pull/6#issuecomment-532212956). Working on it

2019-09-18 17:33 UTC, alexkond submitted a review, later dismissed

2019-09-19 05:18 UTC, savchukm requested changes

2019-09-19 05:18 UTC, savchukm commented on tasks/52_sum-all-numbers-in-range/sum-all-numbers-in-range.js
> +  const roundedLast = Math.floor(last);
Do we really need `ceil` and `floor` function using here?

2019-09-19 05:18 UTC, savchukm commented on tasks/57_pig-latin/pig-latin.js
> +  for (let i = 0; i < textLength && !isVowel(text[0]); ++i) {
You already have` isVowel(first)` above. What is reason of checking it in for loop? Moreover `for` is checking this condition on every condition but the result the same

2019-09-19 08:40 UTC, MatvienkoDO commented on tasks/52_sum-all-numbers-in-range/sum-all-numbers-in-range.js
> +  const roundedLast = Math.floor(last);
there is no information about format of numbers. Whether it is integer or fractional

2019-09-19 12:00 UTC, MatvienkoDO commented on tasks/57_pig-latin/pig-latin.js
> +  for (let i = 0; i < textLength && !isVowel(text[0]); ++i) {
On every iteration it places first letter into the end of string. So, on every iteration text[0] is different

2019-09-20 15:35 UTC, KalachevDev submitted a review, later dismissed

2019-09-24 07:36 UTC, vovcyan approved these changes

2019-09-24 09:24 UTC, savchukm approved these changes

2019-09-24 09:25 UTC, merged